# build

FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

#runtime
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
#docker-compose mounts nginx.conf
