services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: [postgres]
    environment:
      ConnectionStrings__DefaultConnection: Data source=dice.db
      ConnectionStrings__psql: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      JwtSettings__Issuer: ${JWT_ISSUER}
      JwtSettings__Audience: ${JWT_AUDIENCE}
      JwtSettings__Secret: ${JWT_SECRET}
      DefaultPasswords__Administrator: ${ADMIN_PASSWORD}
      DefaultPasswords__RegisteredUser: ${USER_PASSWORD}
    ports:
      # 5267 in container exposed as 5000 in appnet
      - "5000:5267"
    volumes:
      - ./backend:/app
    networks: [appnet]

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on: [backend]
    networks: [appnet]

volumes:
  pgdata:

networks:
  appnet:
