services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]

  backend:
    build:
      context: ./backend
    depends_on: [postgres]
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=rolltale;Username=postgres;Password=yourpassword
    networks: [appnet]

  angular:
    build:
      context: ./frontend
    depends_on: [backend]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on: [frontend, backend]
    networks: [appnet]

volumes:
  pgdata:

networks:
  appnet:
